# Generated by Django 5.2 on 2025-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_video_is_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
