# Generated by Django 5.2 on 2025-05-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_video_subtitles_file_video_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='video',
            name='subtitles_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.DeleteModel(
            name='Subtitle',
        ),
    ]
