# Generated by Django 5.2 on 2025-05-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_video_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitles_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='transcription',
            field=models.FileField(blank=True, null=True, upload_to='transcriptions/'),
        ),
    ]
