# Generated by Django 5.2 on 2025-05-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_video_subtitles_file_alter_video_transcription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subtitles_file',
        ),
        migrations.AddField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
