# Generated by Django 5.2 on 2025-05-19 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subtitles_file',
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subtitle'),
        ),
    ]
